CREATE DATABASE IF NOT EXISTS test;

CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY '1332';
GRANT ALL PRIVILEGES ON test.* TO 'appuser'@'%';
FLUSH PRIVILEGES;

USE test;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE
);
