services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 1332
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: 1332
      DB_DATABASE: test
    volumes:
      - .:/app
    command: sh -c "until timeout 1 bash -c 'cat < /dev/null > /dev/tcp/mysql/3306'; do echo 'Esperando o MySQL subir...'; sleep 2; done && npm run dev"

volumes:
  mysql-data:
